import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"
import { Separator } from "@/components/ui/separator";
import { Toaster } from "sonner";
import { HeaderProfile as HeaderProfile } from "@/components/ui/header-profile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-maternity Portal",
  description: "Generated by create next app",
  
};

export default function PatientsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
            <SidebarProvider defaultOpen={false}>
        <AppSidebar />
        <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 border m-2 rounded-lg bg-sidebar shadow-2xs transition-[width,height] ease-linear sticky top-0 z-50">
            <div className="flex items-center gap-2 px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator
                orientation="vertical"
                className="mr-2 data-[orientation=vertical]:h-4"
              />
            </div>
            <div className="flex">
            </div>
            <div className="flex ml-auto" >
            <HeaderProfile />
            </div>
          </header>
          {children}
          <Toaster />
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
